/** @const {ShadowJS} */ var Promise;
/** @const {ShadowJS} */ var TextEncoder;
/** @const {ShadowJS} */ var Uint8Array;
/** @const {ShadowJS} */ var atob;
/** @const {ShadowJS} */ var btoa;
/** @const {ShadowJS} */ var crypto;
/** @const {ShadowJS} */ var fetch;
/** @const {ShadowJS} */ var localStorage;
/** @const {ShadowJS} */ var module;
/** @const {ShadowJS} */ var setInterval;
ShadowJS.prototype.act;
ShadowJS.prototype.all;
ShadowJS.prototype.exportKey;
ShadowJS.prototype.fromCharCode;
ShadowJS.prototype.generateKey;
ShadowJS.prototype.importKey;
ShadowJS.prototype.parse;
ShadowJS.prototype.resolve;
ShadowJS.prototype.sign;
ShadowJS.prototype.stringify;
ShadowJS.prototype.subtle;
ShadowJS.prototype.tkOn;